"""add nav_status to funds

Revision ID: 112a883b8ecc
Revises: d12c7bf34891
Create Date: 2026-03-06 23:49:50.307349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112a883b8ecc'
down_revision: Union[str, Sequence[str], None] = 'd12c7bf34891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('nav_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'nav_status')
    # ### end Alembic commands ###
