"""expand_products_table_phase4

Revision ID: 6d49d6b0fb67
Revises: df2f52f36b64
Create Date: 2026-03-07 05:12:01.942677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d49d6b0fb67'
down_revision: Union[str, Sequence[str], None] = 'df2f52f36b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('administrator', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('inception_date', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('total_shares', sa.Numeric(precision=16, scale=4), nullable=True))
    op.add_column('products', sa.Column('management_fee_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('products', sa.Column('performance_fee_rate', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('products', sa.Column('high_watermark', sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column('products', sa.Column('linked_portfolio_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'products', 'portfolios', ['linked_portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'notes')
    op.drop_column('products', 'linked_portfolio_id')
    op.drop_column('products', 'high_watermark')
    op.drop_column('products', 'performance_fee_rate')
    op.drop_column('products', 'management_fee_rate')
    op.drop_column('products', 'total_shares')
    op.drop_column('products', 'inception_date')
    op.drop_column('products', 'administrator')
    # ### end Alembic commands ###
