"""initial_schema

Revision ID: b30a683e30bb
Revises: 
Create Date: 2026-03-05 20:41:50.555339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b30a683e30bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_code', sa.String(length=50), nullable=False),
    sa.Column('index_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code')
    )
    op.create_table('composite_benchmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('config_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_name', sa.String(length=200), nullable=False),
    sa.Column('filing_number', sa.String(length=50), nullable=True),
    sa.Column('manager_name', sa.String(length=200), nullable=False),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('strategy_type', sa.String(length=50), nullable=True),
    sa.Column('strategy_sub', sa.String(length=50), nullable=True),
    sa.Column('latest_nav', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('latest_nav_date', sa.Date(), nullable=True),
    sa.Column('nav_frequency', sa.String(length=10), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('fof99_fund_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_number')
    )
    op.create_table('index_nav',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_code', sa.String(length=50), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('nav_value', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('daily_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code', 'nav_date', name='uq_index_nav_code_date')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('portfolio_type', sa.String(length=20), nullable=True),
    sa.Column('allocation_model', sa.String(length=30), nullable=True),
    sa.Column('rebalance_freq', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('custodian', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_calendar',
    sa.Column('cal_date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('cal_date')
    )
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('config_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('nav_series_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composite_benchmark_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('composite_id', sa.Integer(), nullable=False),
    sa.Column('index_code', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['composite_id'], ['composite_benchmarks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('composite_id', 'index_code', name='uq_composite_item_code')
    )
    op.create_table('fund_pools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_type', sa.String(length=20), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_type', 'fund_id', name='uq_fund_pool_type_fund')
    )
    op.create_table('nav_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('unit_nav', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cumulative_nav', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('adjusted_nav', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('daily_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'nav_date', name='uq_nav_history_fund_date')
    )
    op.create_index('ix_nav_history_fund_date', 'nav_history', ['fund_id', 'nav_date'], unique=False)
    op.create_table('portfolio_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('target_weight', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'fund_id', 'effective_date', name='uq_portfolio_alloc_fund_date')
    )
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_added', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('config_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuation_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('total_nav', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('unit_nav', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cumulative_nav', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('total_shares', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'valuation_date', name='uq_valuation_snapshot_product_date')
    )
    op.create_table('valuation_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=30), nullable=True),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('parent_code', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('cost_pct_nav', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('value_pct_nav', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('value_diff', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('linked_fund_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['linked_fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['valuation_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuation_items')
    op.drop_table('valuation_snapshots')
    op.drop_table('scrape_jobs')
    op.drop_table('portfolio_allocations')
    op.drop_index('ix_nav_history_fund_date', table_name='nav_history')
    op.drop_table('nav_history')
    op.drop_table('fund_pools')
    op.drop_table('composite_benchmark_items')
    op.drop_table('backtest_results')
    op.drop_table('trading_calendar')
    op.drop_table('products')
    op.drop_table('portfolios')
    op.drop_table('index_nav')
    op.drop_table('funds')
    op.drop_table('data_sources')
    op.drop_table('composite_benchmarks')
    op.drop_table('benchmarks')
    # ### end Alembic commands ###
