"""add_index_code_to_portfolio_allocations

Revision ID: d12c7bf34891
Revises: 61b5a34e0aa5
Create Date: 2026-03-06 10:20:05.574527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12c7bf34891'
down_revision: Union[str, Sequence[str], None] = '61b5a34e0aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_allocations', sa.Column('index_code', sa.String(length=50), nullable=True))
    op.alter_column('portfolio_allocations', 'fund_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('uq_portfolio_alloc_fund_date'), 'portfolio_allocations', type_='unique')
    op.create_unique_constraint('uq_portfolio_alloc_asset_date', 'portfolio_allocations', ['portfolio_id', 'fund_id', 'index_code', 'effective_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_portfolio_alloc_asset_date', 'portfolio_allocations', type_='unique')
    op.create_unique_constraint(op.f('uq_portfolio_alloc_fund_date'), 'portfolio_allocations', ['portfolio_id', 'fund_id', 'effective_date'], postgresql_nulls_not_distinct=False)
    op.alter_column('portfolio_allocations', 'fund_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('portfolio_allocations', 'index_code')
    # ### end Alembic commands ###
