"""add data_quality_score and data_quality_tags to funds

Revision ID: df2f52f36b64
Revises: 112a883b8ecc
Create Date: 2026-03-07 00:26:35.773932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df2f52f36b64'
down_revision: Union[str, Sequence[str], None] = '112a883b8ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funds', sa.Column('data_quality_score', sa.Integer(), nullable=True))
    op.add_column('funds', sa.Column('data_quality_tags', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funds', 'data_quality_tags')
    op.drop_column('funds', 'data_quality_score')
    # ### end Alembic commands ###
